name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Build app for release
      run: msbuild LongPath.sln -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: Copy files
      run: |
        cp Pri.LongPath.net40\bin\Release\*.* nuget\lib\net40
        cp Pri.LongPath.net20\bin\Release\*.* nuget\lib\net20
        cp Pri.LongPath\bin\Release\*.* nuget\lib\net45
    - name: list file
      run: ls nuget\lib\net45
        
